
  


name: "Sync Self-Hosted Runner Groups"
on:
  schedule:
    # daily at midnight
    - cron:  '0 0 * * *' 

  workflow_dispatch:

jobs:
  sync-runner-groups:
    runs-on: ubuntu-latest
    steps:
    - name: Clone Repository
      uses: actions/checkout@v2
    - uses: JohnNeville/self-hosted-runner-grouper@25852509a5a317f8b68b22bea2730ccb9983504a
      with:
        org-auth-token: "${{ secrets.ORG_ADMIN_MACHINE_USER_PAT }}"